baseURL = "https://hadyang.com/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "HadYang"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-even"
enableGitInfo = false # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。
# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=false"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
hasCJKLanguage = true # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 5 # 首页每页显示的文章数
disqusShortname = "" # disqus_shortname
copyright = "" # 默认为下面配置的author.name ↓

[author]
name = "HadYang"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[[menu.main]]
name = "Interview"
weight = 20
identifier = "interview"
url = "/interview/"

[[menu.main]]
name = "分类"
weight = 30
identifier = "categories"
url = "/categories/"

[params]
version = "4.x" # Used to give a friendly message when you have an incompatible update
debug = false # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
since = "2017" # Site creation time          # 站点建立时间
# 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
gitRepo = ""

# site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
logoTitle = "HadYang" # default: the title value    # 默认值: 上面设置的title值
keywords = ["Java"]
description = "Hugo theme even example site."
archivePaginate = 20 # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
showArchiveCount = false # 是否在归档页显示文章的总数
dateFormatToUse = "2006-01-02" #see https://gohugo.io/functions/format/
moreMeta = true # 是否显示字数统计与阅读时间
highlightInClient = false

# 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
toc = true # 是否开启目录
autoCollapseToc = false                              # 目录自动展开/折叠
fancybox = true # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
mathjax = true # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
mathjaxEnableSingleDollar = true # 是否使用 $...$ 即可進行inline latex渲染
mathjaxEnableAutoNumber = false # 是否使用公式自动编号
mathjaxUseLocalFiles = false # You should install mathjax in `your-site/static/lib/mathjax`
postMetaInFooter = false # contain author, lastMod, markdown link, license           # 包含作者，上次修改时间，markdown链接，许可信息
linkToMarkDown = false # Only effective when hugo will output .md files.           # 链接到markdown原始文件（仅当允许hugo生成markdown文件时有效）
contentCopyright = '' # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
baiduAnalytics = "49f2b1e1a271a64b4ba7d825259ceef9"
customCSS = []
customJS = []
uglyURLs = false # please keep same with uglyurls setting

[params.publicCDN] # load these files from public cdn                          # 启用公共CDN，需自行定义
enable = true
jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

# 在文章开头显示提示信息，提醒读者文章内容可能过时。
[params.outdatedInfoWarning]
enable = false
hint = 30 # 如果文章最后更新于这天数之前，显示提醒
warn = 180 # 如果文章最后更新于这天数之前，显示警告

[params.gitalk] # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
owner = "hadyang" # Your GitHub ID
repo = "hadyang.github.io" # The repo to store comments
clientId = "64b9f11ba0a3291ee49e" # Your client ID
clientSecret = "8632b99db733cc33fd8f6fe85680f63f0db9d872" # Your client secret

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]

[privacy.youtube]
privacyEnhanced = true

[permalinks]
post = "/:year/:month/:filename/"

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
[mediaTypes]
 [mediaTypes."text/plain"]
   suffixes = ["md"]

[outputFormats.MarkDown]
 mediaType = "text/plain"
 isPlainText = true
 isHTML = false

[outputs]
 home = ["HTML"]
 page = ["HTML", "MarkDown"]
 section = ["HTML"]
 taxonomy = ["HTML"]
 taxonomyTerm = ["HTML"]


[markup.goldmark.renderer]
  unsafe = true